apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  namespace: lgcns

spec:
  # 자원공간의 낭비를 방지하고 관리의 편의성을 제공해주는 옵션!!!
  revisionHistoryLimit: 2

  replicas: 1
  selector:
    matchLabels:
      app: config

  template:
    metadata:
      labels:
        app: config

    spec:
      # docker container 
      containers:
        - name: config-container
          # ecr 경로
          image: 310095858382.dkr.ecr.us-east-1.amazonaws.com/config-server:latest
          ports:
          - containerPort: 8080
          resources:
            # container가 사용할 수 있는 최대치의 Resource
            limits:
              cpu: "1"
              memory: "500Mi"
            # Container가 기동할 때 보장 받는 최소 Resource
            requests:
              cpu: "0.5"
              memory: "250Mi"
          
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"


---

apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: lgcns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: config